### ISSUE TITLE
Empty Fish ID Database

### ISSUE THREAD

**Issue by braskasguardian** [svanheulen/fisher-windower-addon#15]
Not sure if anyone else has found this but I am constantly stuck in a loop of releasing fish as soon as they are on the line. Adding some message tracing on my script seems to show that this is because the Fish database collection is always empty. The call to Update Fish from Packet ID 0x115 seems to never work due to the current.item_id always being nil. 

Is there a way this id is supposed to be populated?

**Comment by Inuyushi** [comment]
Are you trying to fish with a Sabiki Rig? Fisher currently doesn't support multiple catches as there are different ID's for Fish x3, Fish x2, and Fish x1.

Also, have you added the fish you wanted to catch by using //fisher fish add "Fish Name" <timetocatch>? Do you have a bait added? I assume you do, as it doesn't cast without these two things populated.

The way Fisher is supposed to work is you add a fish with an unnkown biteID. When you hook that fish, and no fisher intuition goes off, it will wait until the "You don't know how much longer..." warning pops up. It then sends the catch packet to identify the fish. It will update the fishing database once you have a fish.

Also fisher will release items and monsters instantly unless they are in the "//fisher fish" database.

Are you using the latest version of fisher? The following lines are broken and I haven't fixed them yet:
--elseif #arg == 2 and arg[1]:lower() == 'dncmax' then
	--settings.didnotcatchmax = count
	--settings;save('all')

For me these are 737 through 739. Mine are commented out as I havn't had time to go back and fix them. Let me know if I can help anymore.

**Comment by svanheulen** [comment]
The `current.item_id` only gets set if the fish is in the database (in other word you've caught it before with fisher). If `current.item_id` is `nil` the fish will be automatically released if the fish you have set to catch is known in the database.

Here's the issue with that... 
If you catch the fish the first time using a rod X and then try using rod Y, or using a Penguin ring then the fish ID in the database will never match. This will cause it to always automatically release anything you hook. This happens because, as I found recently, my assumptions about the structure of the 0x115 packet were way off (see: http://www.ffxiah.com/forum/topic/49197/exact-effects-of-various-fishing-items/).

Although you can work around it by always using the same fishing rod and always/never using Penguin ring. Or you can reset the fish database before you start fishing.

The real fix would require a major rewrite of the code.

**Comment by Inuyushi** [comment]
Isn't every programming fix just a major rewrite of the code? XD

**Comment by braskasguardian** [comment]
Thank you for replying quickly guys. I am using the latest version tweaked with extra logging.

So my issue appears to be populating the database to start off. I've just started fishing so skill level 1 and I've only been using a Bamboo Fishing Rod with Lugworm bait. I'm currently testing in Port Windurst for "Quus" and "Bastore Sardine" fish. (I can get them both manually). I'm not using any other gear that affects fishing.

Writing to the file "C:\Program Files (x86)\Windower4\addons\fisher\data\<CharacterName>.xml" seems to work fine with the Log level command, so this can't be related to write permissions. Although even after starting the program, the fish tags remain as:

        <fish>

        </fish>

Any ideas on the best way to populate a blank database?

Here is my copy of the database:
http://pastebin.com/8NycZ67A

Here is my copy of the script adjusted for logging:
http://pastebin.com/a46ETikT

**Comment by svanheulen** [comment]
Oh actually, they `current.item_id` is set based on the message IDs for the zone. It's possible that the message IDs just need to be updated.

To do that just run the Python script in the `messages` folder, which will create a new `messages.lua` file in that folder. Copy that new file to the `fisher` folder and replace the old one. Let me know if that works.

**Comment by braskasguardian** [comment]
That's fixed it! Thanks for the advice svanheulen. Seems the messages.lua was out of date then.

**Comment by svanheulen** [comment]
Cool, glad that worked, and thanks for the pull requests :)
