### ISSUE TITLE
No longer detects/catches

### ISSUE THREAD

**Issue by Mercurian** [svanheulen/fisher-windower-addon#20]
It doesn't seem to be able to identify fish anymore, and therefor won't reel in anything

**Comment by svanheulen** [comment]
The `messages.lua` file needs to be updated after any game update that modifies the dialog tables in certain ways. If you check the "messages" folder in this repo there's a script that will rebuild the `messages.lua` file for you.

Please make a pull request with the fixed `messages.lua` file.

I'm going to leave this issue open indefinitely since I get this question quite often.

**Comment by Mercurian** [comment]
God I'm so bad at github and lua, can you explain it the kindergarten way qq

**Comment by Mercurian** [comment]
Now, it's not releasing items lol

**Comment by svanheulen** [comment]
1. Install [Python 3.x](https://www.python.org).
2. Double click on the `messages\make_messages.py` file. Once it completes you'll have a new `messages\messages.lua` file.
3. Replace the `messages.lua` file in the main folder with the new one.

As for the pull request, don't worry about it. Someone else will send it eventually.

**Comment by Mercurian** [comment]
I did all that, but now its not even releasing unwanted fish/items in addition to not identifying/catching the ones i'm looking for.

(btw, how can I make it just catch everything?) Instead of singling one fish out.

**Comment by svanheulen** [comment]
That's because fisher doesn't know of any fish/items when you first start using it. It needs to learn. If you hook a fish/item that isn't in your database it will wait until the fish/item is about to escape and then catch it. When it catches a fish/item for the first time it adds it to the database.

If you did have the fish in your database, it's possible that your database got messed up and you should reset/clear it with the `resetdb` command. And also keep in mind that the addon needs to be reloaded if you're still running the game when you modified the `messages.lua` file.

And no, there is currently no way to make it catch everything. You can add as many fish as you want to the catch list though.

**Comment by sebyg666** [comment]
the python file is not making a new messages.lua, do i have to be logged out of game for it to work?

**Comment by Mercurian** [comment]
I deleted the old one, then ran it. I thought it was doing nothing, but then after a couple minutes it created the file.

(had never used python before)

**Comment by sebyg666** [comment]
is the python thing only for US versions because mine is EU

**Comment by sebyg666** [comment]
any chance u can send me ur messages.lua file please mercurian?
can email it at sebyg666@hotmail.com

**Comment by Mercurian** [comment]
I will sure, important note:

you have to manually catch the fish youre targetting once, so it populates the file, mine will only have giant catfish, as it's the fish I was trying to catch.

**Comment by svanheulen** [comment]
@sebyg666 Yes, the Python script is for the US version of the game, but you can easily fix it to work with the EU version. Just change the "US" on [this line](https://github.com/svanheulen/fisher-windower-addon/blob/master/messages/make_messages.py#L10) to "EU" and it should work.

**Comment by sebyg666** [comment]
haha its doin stuff now, excellent ty, will post back if i get it working, thanks for the quick replize

**Comment by svanheulen** [comment]
When it's learning, it waits until the fish is about the escape (the "You don't know how much longer you can keep this one on the line..." message) before it catches it. The reason for that is because it doesn't know what fish/item is on the line. The delay you have set may be way too short for what's actually on the line. For instance if you have a 1 second delay set to catch Rusty Buckets and you hook a Maysta... it would look very suspicions if you pulled up a Matsya in 1 second. But once a fish/item is in your database it will use the proper delay the next time you hook it.

**Comment by sebyg666** [comment]
i thaught so, thanks again

**Comment by m1shi** [comment]
Hey,
I did all the updates to the message file and whatnot, the fisher does catch fishies like it did before, but i did run into a small issue. Now each time somethin gets hooked i get this info in the console:
the id of cought thing table: and another set of numbers and letters, im wonderrin if i updated somethin wrongly or its just an occuring issue with fisher.
