### ISSUE TITLE
Crashing on Ferry

### ISSUE THREAD

**Issue by TDayneBarton** [svanheulen/fisher-windower-addon#28]
After the Byrth update, I tried to catch a Gugru on the ship to Aht Urghan. The box that usually shows up to show all the catch stats was completely black (no text). As I had cleared my database, this was the first time I had caught Gurgu's since getting my Ebisu. Fisher waited until running out of time to send the catch packet.

After sending the catch packet, the whole game crashed. I didn't catch the notification as to why windower crashed as I'm tired, but it was a full crash to my desktop. Any ideas why this could happen? I haven't had any issues other than on a Ferry.

**Comment by TDayneBarton** [comment]
Update: I turned off the newly added @Byrth features. When hooking the first Gugru, the screen locked for about 5 seconds. After unfreezing, I was able to catch the Gugru manually because there was no notification for catching the fish at Low HP. After catching the first Gugru, I hooked a Cobalt Jellyfish. Fisher proceeded to catch it before timing out and I crashed again. I got a picture of the crash details this time.

<a href="http://s25.photobucket.com/user/Inuyushi/media/Capture_1.jpg.html" target="_blank"><img src="http://i25.photobucket.com/albums/c51/Inuyushi/Capture_1.jpg" border="0" alt="Fisher error photo Capture_1.jpg"/></a>

This may be unrelated, but after logging back in, loading up fisher, and experiencing the same issues above. I unloaded the addon. While the addon was unloaded, I crashed zoning into Mhaura. I've been using the dgVoodooCpl settings with Windower4, any chance this could be related to the above issues?

**Comment by TDayneBarton** [comment]
Another update: I pulled the last stable version before the Byrth changes and it's working fine. I'm going to scratch off dgVoodoo as the source of the issue.

@Byrth any ideas as to what could cause this?

**Comment by Byrth** [comment]
It is some kind of lockup? I'm not quite sure. I think it has to do with creating and displaying the primitive. If you comment out everything related to the display features then it might fix it.

**Comment by DulceNimue** [comment]
I also came across this issue today, is there a fix as of yet that I am not seeing in this thread? It is a consistent crash, however it did let me catch some fish. As with the person before the stats window in the upper left corner turns black, it occasionally lets me try to manually catch the fish but upon sending the catch command it crashes. The crash only happens when the above window turns black. I did have a few lengthy screen freezes, with no crash as well. 

I have restarted my PC, cleared caches, Fisher database, re-installed Windower and ran it with only the Fisher plugin and still encountered the same error. 

The error does not give much this is what it says : 

Microsoft Visual C++ Runtime Library 
Runtime Error: 
Program C:\Program ... 
This application has requested the Runtie to terminate it in 
an unusual way. 
Please contact the application's support team for more information. 

The addon was working fine before boarding the Ferry, Windower does not crash with out the addon running or in other zones. I was fishing fine for a while before have not tried to fish elsewhere yet as I have been stubbornly trying to figure this out all morning. I am skilling up of Ferry fish currently and completing Tenacity RoE.

**Comment by TDayneBarton** [comment]
Yeah, the issue is related only to Ferry fishing. Like Byrth said, if you comment out the lines that apply to it, you can fish on the Ferry again.

**Comment by DulceNimue** [comment]
How do you comment out the lines that apply to it? 

I am now having the issue fishing Lik in Luffaise Meadows as well. It bites, the screen freezes, the info box at the top does not even pop up, I can catch it the box comes back the I crash.

**Comment by TDayneBarton** [comment]
You have to place two dashes '--' in front of any line that contains 'fish_box' or 'fishboxstats' to disable the box from showing up. These show up from line 66-69 & 430-443 (this whole function is unnecessary excepte to show the box).

You can also do '--[[' in front of the first line of text and then ']]--' after the last line you want to comment out to comment a whole block of code.

I hope this helps!
