### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by DulceNimue** [svanheulen/fisher-windower-addon#42]
Hello! 

I am crashing when I fish up Lik or Gugurusaurous is this supposed to happen? It seems to only be with those two fishes. I do have comment boxes taken out as suggested for Ferry Fishing. 

The crash is similar to the Ferry Fishing, I will get the bite it will notify me screen freezes, I will get the error that the program has experienced an issue it gives me the option to wait if I wait it out the character will unfreeze for a moment then RO. Only the fishing character will RO I've been doing missions on a mule at the same time, mule is fine main fisher RO's.  

Is there any suggestions? Do I need a new messages.txt? I still have not figured out how to create those :( 

Thank you so very much for your time and continued help!

**Comment by TDayneBarton** [comment]
I honestly have no idea. I don't use fisher anymore since I got all the items from fishing that I wanted. It could be a new messages needs made, but usually that doesn't make it crash. Needing a new messages would make it release when it shouldn't. 

If you want to run messages, you need to download a program that executes python. I reformatted my PC and didn't put that part back on yet. Also, the make_message.py has an error in it. I forget where, but I fixed it in my version. I havn't uploaded it though, sorry. All in all, if you want to make this program work you have to become your own programmer and figure it out as the original developer has gone MIA. Sorry buddy :(

**Comment by DulceNimue** [comment]
No worries thank you for replying regardless!

**Comment by svanheulen** [comment]
It's not so much that I'm MIA and more that there's nothing I can do. I don't play FFXI any more so I have no way of troubleshooting. Sorry, I can't be more helpful.
